# -----------------------------
# Options affecting formatting.
# -----------------------------
format:

  # How wide to allow formatted cmake files
  line_width: 120

  # How many spaces to tab for indent
  tab_size: 2

  # If true, lines are indented using tab characters (utf-8 0x09) instead of
  # <tab_size> space characters (utf-8 0x20). In cases where the layout would
  # require a fractional tab character, the behavior of the  fractional
  # indentation is governed by <fractional_tab_policy>
  use_tabchars: False

  # If an argument group contains more than this many sub-groups (parg or kwarg
  # groups) then force it to a vertical layout.
  max_subgroups_hwrap: 2

  # If a positional argument group contains more than this many arguments, then
  # force it to a vertical layout.
  max_pargs_hwrap: 6

  # If true, separate flow control names from their parentheses with a space
  separate_ctrl_name_with_space: False

  # If true, separate function names from parentheses with a space
  separate_fn_name_with_space: False

  # If a statement is wrapped to more than one line, than dangle the closing
  # parenthesis on its own line.
  dangle_parens: true

  # If the trailing parenthesis must be 'dangled' on its on line, then align it
  # to this reference: `prefix`: the start of the statement,  `prefix-indent`:
  # the start of the statement, plus one indentation  level, `child`: align to
  # the column of the arguments
  dangle_align: 'prefix'



# -------------------------------------
# Additional commands
# -------------------------------------
parse:
  additional_commands:
    CPMAddPackage:
      pargs:
        nargs: '*'
        flags: []
      spelling: CPMAddPackage
      kwargs:
        NAME: 1
        FORCE: 1
        VERSION: 1
        GIT_TAG: 1
        DOWNLOAD_ONLY: 1
        GITHUB_REPOSITORY: 1
        GITLAB_REPOSITORY: 1
        GIT_REPOSITORY: 1
        SVN_REPOSITORY: 1
        SVN_REVISION: 1
        SOURCE_DIR: 1
        DOWNLOAD_COMMAND: 1
        FIND_PACKAGE_ARGUMENTS: 1
        NO_CACHE: 1
        GIT_SHALLOW: 1
        URL: 1
        URL_HASH: 1
        URL_MD5: 1
        DOWNLOAD_NAME: 1
        DOWNLOAD_NO_EXTRACT: 1
        HTTP_USERNAME: 1
        HTTP_PASSWORD: 1
        OPTIONS: +
    ProjectMeta:
      pargs:
        nargs: '*'
        flags: []
      spelling: ProjectMeta
      kwargs:
        PROJECT_ID: 1
        PROJECT_ID_LOWER: 1
        PROJECT_NAME: 1
        PROJECT_NAME_LOWER: 1
        PROJECT_DESCRIPTION: 1
        PROJECT_NAMESPACE: 1
        PROJECT_COPYRIGHT: 1
        PROJECT_URL: 1
        AUTHOR_ORGANIZATION: 1
        AUTHOR_DOMAIN: 1
        AUTHOR_MAINTAINER: 1
        VERSION_MAJOR: 1
        VERSION_MINOR: 1
        VERSION_PATCH: 1
        VERSION_REVISION: 1
        VERSION: 1
        VERSION_NAME: 1
    generate_export_header:
      pargs:
        nargs: '*'
        flags: []
      spelling: generate_export_header
      kwargs:
        BASE_NAME: 1
        EXPORT_FILE_NAME: 1
