name: Documentation

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-20.04
    steps:

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libclang1-9 libclang-cpp9

      - name: Doxygen 1.9.2
        env:
          DOXYGEN_VERSION: 1.9.2
          TMP: ${{ github.workspace }}/tmp
        run: |
          mkdir -p $TMP/doxygen
          cd $TMP/doxygen
          wget http://www.doxygen.nl/files/doxygen-$DOXYGEN_VERSION.linux.bin.tar.gz
          gunzip doxygen-$DOXYGEN_VERSION.linux.bin.tar.gz
          tar -xf doxygen-$DOXYGEN_VERSION.linux.bin.tar
          cd doxygen-$DOXYGEN_VERSION
          sudo make install
          doxygen --version

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure cache
        uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ runner.os }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt') }}-${{ hashFiles('**/*.cmake') }}

      - name: Build
        run: |
          cmake -S doc -B build
          cmake --build build --target generate_documentation

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
